CI updates after review

diff --git a/.github/workflows/nested_eagle.yml b/.github/workflows/nested_eagle.yml
--- a/.github/workflows/nested_eagle.yml
+++ b/.github/workflows/nested_eagle.yml
@@ -24,7 +24,7 @@ jobs:
       - name: Add a ci-running label
         uses: actions-ecosystem/action-add-labels@v1
         with:
-          labels: 'ci-running' # Adding ci-running label to prevent duplicate runs.
+          labels: "ci-running" # Adding ci-running label to prevent duplicate runs.
           github_token: ${{ secrets.GITHUB_TOKEN }}
       - name: Submit Initial Grids
         run: |
@@ -140,33 +140,30 @@ jobs:
       - name: Perform grid2obs verification with wxvx
         run: |
           cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2obs
-          JOB_ID1=$(sbatch submit_obs_verification.sh | awk '{print $4}')
-          echo "Submitted Grid_to_Obs Verification Slurm job with ID: $JOB_ID1"
+
+          JOB_ID1=$(submit_obs_verification.sh | awk '{print $4}')
 
           cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2grid
-          JOB_ID2=$(sbatch submit_grid_verification.sh | awk '{print $4}')
-          echo "Submitted Grid_to_Grid Verification Slurm job with ID: $JOB_ID2"
 
-          for JOB in $JOB_ID1 $JOB_ID2; do
-            echo "Waiting for job $JOB to complete..."
-            while squeue -h -j ${JOB} | grep -q "${JOB}"; do
-               squeue -j $JOB
-               sleep 30  # Wait for 30 seconds before checking again.
-            done
-            echo "Slurm job $JOB to perform verification has been completed."
+          JOB_ID2=$(submit_grid_verification.sh | awk '{print $4}')
 
-          cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2obs/wxvx_workdir
-          find ./lam -name "*.png" -print -quit | grep -q . || { echo "Error: No LAM grid2obs verification plots found."; exit 1; } 
-          find ./global -name "*.png" -print -quit | grep -q . || { echo "Error: No global grid2obs verification plots found."; exit 1; } 
-          echo "Grid2obs Verification process has been successfully completed."
+             echo "Submitted Slurm job with ID: $JOB_ID1"
+             echo "Submitted Slurm job with ID: $JOB_ID2"
+             while squeue -h -j ${JOB_ID1},${JOB_ID2} | grep -q "${JOB_ID1}\|${JOB_ID2}"; do
+                squeue -j ${JOB_ID1},${JOB_ID2}
 
-          cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2grid/wxvx_workdir
-          find ./lam -name "*.png" -print -quit | grep -q . || { echo "Error: No LAM grid2grid verification plots found."; exit 1; } 
-          find ./global -name "*.png" -print -quit | grep -q . || { echo "Error: No global grid2grid verification plots found."; exit 1; } 
-          echo "Grid2grid Verification process has been successfully completed."
+            cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2obs/wxvx_workdir
+            find ./lam -name "*.png" -print -quit | grep -q . || { echo "Error: No LAM grid2obs verification plots found."; exit 1; } 
+            find ./global -name "*.png" -print -quit | grep -q . || { echo "Error: No global grid2obs verification plots found."; exit 1; } 
+            echo "Grid2obs Verification process has been successfully completed."
+
+            cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2grid/wxvx_workdir
+            find ./lam -name "*.png" -print -quit | grep -q . || { echo "Error: No LAM grid2grid verification plots found."; exit 1; } 
+            find ./global -name "*.png" -print -quit | grep -q . || { echo "Error: No global grid2grid verification plots found."; exit 1; } 
+            echo "Grid2grid Verification process has been successfully completed."
       - name: Remove label from pull request
         if: always()
         uses: mondeja/remove-labels-gh-action@v2.0.0
         with:
-          labels: 'ci-running'
+          labels: "ci-running"
           token: ${{ secrets.GITHUB_TOKEN }}
